In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print("Tensorflow version " + tf.__version__)

try:
  tpu = tf.distribute.cluster_resolver.TPUClusterResolver()  # TPU detection
  tf.config.experimental_connect_to_cluster(tpu)
  tf.tpu.experimental.initialize_tpu_system(tpu)
  tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)
  print('Running on TPU ', tpu.cluster_spec().as_dict()['worker'])
except ValueError:
  raise BaseException('ERROR: Not connected to a TPU runtime; please see the previous cell in this notebook for instructions!')

from google.colab import drive
drive.mount('/content/drive')

Tensorflow version 2.8.0
INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.


INFO:tensorflow:Deallocate tpu buffers before initializing tpu system.


INFO:tensorflow:Initializing the TPU system: grpc://10.27.140.98:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.27.140.98:8470


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


Running on TPU  ['10.27.140.98:8470']


In [157]:
# multivariate multi-step stacked lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
import matplotlib.pyplot as plt
from pandas import read_csv
import math
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from keras.layers.core import Dense, Activation, Dropout
from datetime import datetime
import time
from keras.activations import *
import tensorflow as tf
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
#sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
scaler  = MinMaxScaler()
df_train =0
df_test  =0
carpan =1
name   ="M1_hazirVeri_toplu_2008-2022_dongulu"
dbname ="M1_2008-2022_df_dongulu" #"M1_dataframes_4March_dongulu"

"""def TimeStamps(dataframe_Date):
    dTime = dataframe_Date
    if name == ('Weekly'or 'Daily' or 'Monthly'):
        return pd.DataFrame(array([datetime.strptime((dTime[i]),'%Y %m %d').timestamp() for i in range(len(dTime))]))#%H:%M:%S
    else :
        return pd.DataFrame(array([datetime.strptime((dTime[i]),'%Y %m %d %H %M %S').timestamp() for i in range(len(dTime))]))
"""
import dill
try:
    """
    df = read_csv('/content/drive/Othercomputers/2022 Masaüstü 2/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_'+name+'.csv', engine='python')
    #df_test  = read_csv('/content/drive/Othercomputers/2022 Masaüstü 2/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_'+name+'.csv', engine='python')
    #df_train['Date'] = TimeStamps(df_train['Date'])
    #df_test['Date']  = TimeStamps(df_test['Date'])
    dill.dump_session('/content/drive/Othercomputers/2022 Masaüstü 2/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/'+dbname+'.db')
    """
    dill.load_session('/content/drive/Othercomputers/2022 Masaüstü 2/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/'+dbname+'.db')
    
except:
    """
    df = read_csv('C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_'+name+'.csv', engine='python')
    #df_test  = read_csv('C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_'+name+'.csv' , engine='python')
    #df_train['Date'] = TimeStamps(df_train['Date'])
    #df_test['Date']  = TimeStamps(df_test['Date'])
    dill.dump_session('C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/'+dbname+'.db')
    """
    dill.load_session('C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/'+dbname+'.db')
    
df

Unnamed: 0     Open     High      Low    Close      sin      cos
0                 0  1.40760  1.40760  1.40760  1.40760  0.90759  4.82194
1                 1  1.40740  1.40750  1.40740  1.40750  1.00531  4.78443
2                 2  1.40760  1.40810  1.40760  1.40800  1.09857  4.73691
3                 3  1.40810  1.40850  1.40790  1.40820  1.18636  4.67990
4                 4  1.40830  1.40970  1.40830  1.40920  1.26770  4.61402
...             ...      ...      ...      ...      ...      ...      ...
4871851     4871851  1.12726  1.12728  1.12714  1.12718  0.97922  3.44564
4871852     4871852  1.12716  1.12720  1.12712  1.12712  1.03623  3.53343
4871853     4871853  1.12716  1.12718  1.12713  1.12715  1.10211  3.61477
4871854     4871854  1.12715  1.12728  1.12711  1.12725  1.17612  3.68878
4871855     4871855  1.12726  1.12726  1.12714  1.12716  1.25746  3.75466

[4871856 rows x 7 columns]

In [166]:
sin = df['sin']
cos = df['cos']
open = df['Open']#*100
high = df['High']#*100
low = df['Low']#*100
close = df['Close']#*100

giris=2
cikis=4


date =  pd.concat([sin,cos],axis=1)
if(giris==3):
  date = pd.concat([sin,cos,open],axis=1)
sec =  pd.concat([open,high,low,close],axis=1)
if(cikis==3):
  sec =  pd.concat([high,low,close],axis=1)
  
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(date,sec,test_size=0.1,shuffle=False)


In [167]:
X_test

sin      cos
4384670 -0.22367  1.82052
4384671 -0.19658  1.71941
4384672 -0.18021  1.61603
4384673 -0.17473  1.51150
4384674 -0.18021  1.40697
...          ...      ...
4871851  0.97922  3.44564
4871852  1.03623  3.53343
4871853  1.10211  3.61477
4871854  1.17612  3.68878
4871855  1.25746  3.75466

[487186 rows x 2 columns]

In [168]:
model = Sequential()
units=giris
dense=cikis

print("Orjinal Shape X_train:",X_train.shape)
print("Orjinal Shape X_test:",X_test.shape)
print("Orjinal Shape y_train:",y_train.shape)
print("Orjinal Shape y_train:",y_test.shape)

X_train = np.array(X_train).reshape((len(X_train),1,giris))
X_test = np.array(X_test).reshape((len(X_test),1,giris))
y_train = np.array(y_train).reshape((len(y_train),1,cikis))
y_test = np.array(y_test).reshape((len(y_test),1,cikis))
print("Yeni Shape X_train :",X_train.shape)
print("Yeni Shape X_test :",X_test.shape)
print("Yeni Shape y_train :",y_train.shape)
print("Yeni Shape y_train :",y_test.shape)
model.add(LSTM(units, activation='relu',input_shape=(X_train.shape[1],giris)))

model.add(Dense(4))
model.add(Dropout(0.2))
model.add(Dense(4))
model.add(Dropout(0.2))
model.add(Dense(4))
model.add(Dropout(0.2))
model.add(Dense(4))
model.add(Dropout(0.2))
model.add(Dense(4))
model.add(Dropout(0.5))
model.add(Dense(4))
model.add(Dense(cikis))
opt = tf.keras.optimizers.SGD(learning_rate=0.001)
model.compile(optimizer=opt, loss='mse', metrics=['accuracy'])
print(model.summary())


Orjinal Shape X_train: (4384670, 2)
Orjinal Shape X_test: (487186, 2)
Orjinal Shape y_train: (4384670, 4)
Orjinal Shape y_train: (487186, 4)
Yeni Shape X_train : (4384670, 1, 2)
Yeni Shape X_test : (487186, 1, 2)
Yeni Shape y_train : (4384670, 1, 4)
Yeni Shape y_train : (487186, 1, 4)
Model: "sequential_27"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_13 (LSTM)              (None, 2)                 40        
                                                                 
 dense_95 (Dense)            (None, 4)                 12        
                                                                 
 dropout_55 (Dropout)        (None, 4)                 0         
                                                                 
 dense_96 (Dense)            (None, 4)                 20        
                                                                 
 dropout_56 (Dropout)        (N

In [ ]:
#for i in range(100):
history = model.fit(X_train,y_train, epochs=1,batch_size=1024*2,validation_data=(X_test,y_test))  


 610/2141 [=======>......................] - ETA: 37s - loss: 0.0313 - accuracy: 0.2716

In [ ]:
predict = model.predict(X_test)#.round(5)


In [ ]:
predict2 = np.array(predict).reshape(len(predict),4)
y_test2 = np.array(y_test).reshape(len(y_test),4)
predict2 = pd.DataFrame(predict2,columns=['Open','High','Low','Close'])
y_test2  = pd.DataFrame(y_test2,columns=['Open','High','Low','Close'])
total = pd.concat([predict2,y_test2],axis=1)
print(total)

h1 units 16 1.8535e-06
h1 units 32 1.9282e-06

In [99]:
predict = model.predict(X_test[-250:])#.round(5)

In [100]:
predict

array([[[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434103]],

       [[1.3440524, 1.3453964, 1.349829 , 1.3434

In [83]:
y_test

array([[[1.29749, 1.29752, 1.29728, 1.29737]],

       [[1.29738, 1.29769, 1.29738, 1.29744]],

       [[1.29744, 1.29751, 1.29695, 1.29697]],

       ...,

       [[1.12716, 1.12718, 1.12713, 1.12715]],

       [[1.12715, 1.12728, 1.12711, 1.12725]],

       [[1.12726, 1.12726, 1.12714, 1.12716]]])

In [81]:
print(predict)
print(((predict-y_test)))#.round(5)
predict = scaler.inverse_transform(predict)
y_test  = scaler.inverse_transform(y_test)

fark2 = predict[:50]-y_test[:50]

predict = pd.DataFrame(((predict)),columns=['High_Predict','Low_Predict','Close_Predict'])
y_test = pd.DataFrame(((y_test)),columns=['High_Reel','Low_Reel','Close_Reel'])
X_test = pd.DataFrame(((X_test)),columns=['Open'])


found  = pd.concat([X_test,predict],axis=1)
expect = pd.concat([X_test,y_test],axis=1)
print((predict[i]/carpan).round(5),(y_test[i]/carpan).round(5))
print(fark2,"\n \n",expect,"\n \n",found)

[[[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1.2992302]]

 [[1.2963264 1.2954638 1.2892107 1

ValueError: ignored

In [ ]:
test= X_test.reshape(56086,2)
yy   = y_test.reshape(56086,3)
pre = np.array(predict).reshape(56086,3)
plt.plot(test[0],[yy[0],yy[1],yy[2]],color='blue')
plt.plot(test[0],[pre[0],pre[1],pre[2]],color='red')

In [ ]:
yeni = np.array([1.09160])

model.predict(yeni.reshape(-1,1))#.round(5)

In [ ]:
#from tensorflow.python.client import device_lib
#import tensorflow as tf
#tf.debugging.set_log_device_placement(True)
#print(device_lib.list_local_devices())